added error correction for testing

diff --git a/bin/vdjpuzzle b/bin/vdjpuzzle
--- a/bin/vdjpuzzle
+++ b/bin/vdjpuzzle
@@ -22,17 +22,18 @@ SHARE_DIR=$BIN_DIR/../share
 >&2 echo "Running on date: " `date`
 
 function printHelp {
-	>&2 echo "VDJ Puzzle v1.0"
-	>&2 echo "Usage: ./VDJPuzzle.sh directory_name [option]"
+	>&2 echo "VDJPuzzle v2.0"
+	>&2 echo "Usage: ./vdjpuzzle directory_name [option]"
 	>&2 echo -e "--qsub\texecutes on the cluster (overrides --CPU flag)"
 	>&2 echo -e "--type=(t|b)\tspecifies tcell (default) or bcell analysis"
 	>&2 echo -e "--CPU=n\truns with n processes"
 	>&2 echo -e "--THR=n\truns bowtie and tophat with n threads (default 8)"
 	>&2 echo -e "--species=(human|mouse)\tspecified human (default) or mouse organism"
-	>&2 echo -e "--only-statistics\texecutes only summary statistics script"
-	>&2 echo -e "--no-statistics\tdo not execute summary statistics script"
+	>&2 echo -e "--err-corr\tPerform final error correction on consensus sequence"
+	>&2 echo -e "--only-statistics\tExecutes only summary statistics script"
+	>&2 echo -e "--no-statistics\tDo not execute summary statistics script"
 	>&2 echo -e "--transcriptomic\tEnable cuffquant/cuffnorm gene quantification measurements"
-	>&2 echo -e "--trim\tTrims reads using Trimmomatic"
+	>&2 echo -e "--trim\tTrim reads using Trimmomatic"
 	>&2 echo -e "--counts\tEnable featureCounts gene quantification measurements"
 }
 
@@ -106,6 +107,7 @@ export AVGQUAL=20
 
 #SET DEFAULT PARAMETERS
 PARALLEL=1
+ERRCORR=0
 NTHREADS=1
 COUNTS=0
 RUNTCR=1
@@ -173,6 +175,11 @@ do
 			printHelp
 			exit
 		fi
+		shift
+		;;
+
+		--err-corr)
+		ERRCORR=1
 		shift
 		;;
 
@@ -532,127 +539,126 @@ fi
 # wait for cuffnorm to finish
 waitForProcess cuff $TYPE
 
-# ERROR CORRECTION
-# Requires fasta file of reference (reconstructed) sequences and paired end reads
-# Will run migmap, take identified sequences, align reads and produce the corrected consensus sequence
+if [[ $ERRCORR -ge 1 ]] ; then
+	# ERROR CORRECTION
+	# Requires fasta file of reference (reconstructed) sequences and paired end reads
+	# Will run migmap, take identified sequences, align reads and produce the corrected consensus sequence
 
-# export PATH=/apps/bwa/0.7.12/:$PATH
-# export PATH=/home/fzl561/scRNAseq/Tools/bcftools-1.3.1/bin/:$PATH
+	# export PATH=/apps/bwa/0.7.12/:$PATH
+	# export PATH=/home/fzl561/scRNAseq/Tools/bcftools-1.3.1/bin/:$PATH
 
-# for chain in "${CHAIN_ARRAY[@]}"
-# do
-# 	R1="reads_${chain}_1.fastq"
-# 	R2="reads_${chain}_2.fastq"
+	for chain in "${CHAIN_ARRAY[@]}"
+	do
+		R1="reads_${chain}_1.fastq"
+		R2="reads_${chain}_2.fastq"
 
-# 	# Set up fasta filename containing all reconstructed sequences
-# 	if [[ $TYPE == 't' ]] ; then
-# 		# tcr_[ab].fa
-# 		ORIG_REF="$(echo $chain | tr '[:upper:]' '[:lower:]' | sed -e 's/^.\{3\}/&_/').fa"
-# 	else
-# 		# ig_[hkl].fa
-# 		ORIG_REF="$(echo $chain | tr '[:upper:]' '[:lower:]' | sed -e 's/^.\{2\}/&_/').fa"
-# 	fi
+		# Set up fasta filename containing all reconstructed sequences
+		if [[ $TYPE == 't' ]] ; then
+			# tcr_[ab].fa
+			ORIG_REF="$(echo $chain | tr '[:upper:]' '[:lower:]' | sed -e 's/^.\{3\}/&_/').fa"
+		else
+			# ig_[hkl].fa
+			ORIG_REF="$(echo $chain | tr '[:upper:]' '[:lower:]' | sed -e 's/^.\{2\}/&_/').fa"
+		fi
 
-# 	# create directory for storing results
-# 	OUTPUT=$CURDIR/"$(echo ${chain//c} | tr '[:upper:]' '[:lower:]')"_err_corr
+		# create directory for storing results
+		OUTPUT=$CURDIR/"$(echo ${chain//c} | tr '[:upper:]' '[:lower:]')"_err_corr
 
-# 	echo "CURDIR:\t$CURDIR\nR1:\t$R1\nR2:\t$R2\nORIG_REF:\t$ORIG_REF\nOUTPUT:\t$OUTPUT\n"
-# 	exit
+		# echo "CURDIR:\t$CURDIR\nR1:\t$R1\nR2:\t$R2\nORIG_REF:\t$ORIG_REF\nOUTPUT:\t$OUTPUT\n"
+		# exit
 
-# 	if [[ -e $OUTPUT ]]
-# 	then
-# 		echo "Output directory already exits, exiting ..."
-# 		exit 1
-# 	fi
-# 	mkdir $OUTPUT
+		if [[ -e $OUTPUT ]]
+		then
+			echo "Output directory already exits, removing it"
+			rm -vr $OUTPUT
+		fi
+		mkdir $OUTPUT
 
-# 	for cell in $CURDIR/TCRsequences/*
-# 	do
-# 		# read original data
-# 		ALL_FASTA=$cell$ORIG_REF
-# 		READS_1=$cell$R1
-# 		READS_2=$cell$R2
+		for cell in $CURDIR/TCRsequences/*
+		do
+			# read original data
+			ALL_FASTA=$cell$ORIG_REF
+			READS_1=$cell$R1
+			READS_2=$cell$R2
 
-# 		# skip the case/cell where a directory does not have required files
-# 		if [ -e $ALL_FASTA -a -e $READS_1 -a -e $READS_2 ]
-# 		then
-# 			echo "[current] Reference file and reads found."
-# 			sleep 2
-# 		else
-# 			echo "[current] Reference file and reads were not found ... moving to next cell."
-# 			continue
-# 		fi
+			# skip the case/cell where a directory does not have required files
+			if [ ! -e $ALL_FASTA -a ! -e $READS_1 -a ! -e $READS_2 ]
+			then
+				echo "Reference file and/or reads were not found ... moving to next cell."
+				continue
+			fi
 
-# 		# create subdirectory for each cell analysed
-# 		mkdir $OUTPUT/$(basename $cell)
-# 		cd $OUTPUT/$(basename $cell)
+			# create subdirectory for each cell analysed
+			mkdir $OUTPUT/$(basename $cell)
+			cd $OUTPUT/$(basename $cell)
 
-# 		# construct path for final output file
-# 		CORR_SEQ=$OUTPUT/$(basename $cell)/new_$ORIG_REF
-# 		rm -vf accepted_seq_names.txt
+			# construct path for final output file
+			CORR_SEQ=$OUTPUT/$(basename $cell)/new_$ORIG_REF
+			rm -vf accepted_seq_names.txt
 
-# 		# orange.intersect
-# 		if [[ $(hostname) == 'orange' ]] ; then
-# 			$JAVA18 -jar $MIGMAP -S human --by-read -R $CHAIN_TYPE $ALL_FASTA - |
-# 		else
-# 			# sudo required for write permission on cluster
-# 			sudo $JAVA18 -jar $MIGMAP -S human --by-read -R $CHAIN_TYPE $ALL_FASTA - |
-# 		fi
+	# 		# orange.intersect
+	# 		if [[ $(hostname) == 'orange' ]] ; then
+				$JAVA18 -jar $MIGMAP -S human --by-read -R $CHAIN_TYPE $ALL_FASTA - |
+	# 		else
+	# 			# sudo required for write permission on cluster
+	# 			sudo $JAVA18 -jar $MIGMAP -S human --by-read -R $CHAIN_TYPE $ALL_FASTA - |
+	# 		fi
 
-# 		# first tab delimited entry from migmap is the sequence name
-# 		# create a file with names of identified sequences
-# 		cut -f1 | while read x ; do
-# 				if [[ "$x" == ">"* ]] ; then
-# 					echo "$x" >> accepted_seq_names.txt;
-# 				fi;
-# 			done
+			# first tab delimited entry from migmap is the sequence name
+			# create a file with names of identified sequences
+			cut -f1 | while read x ; do
+					if [[ "$x" == ">"* ]] ; then
+						echo "$x" >> accepted_seq_names.txt;
+					fi;
+				done
 
-# 		rm -vf $CORR_SEQ
+			rm -vr $CORR_SEQ
 
-# 		# go through identified sequences and use as reference for alignment
-# 		while read seq_name; do
-# 			# create a fasta reference file with a single sequence, index it as required
-# 			python $CURDIR/extract_fasta.py "$seq_name" $ALL_FASTA # creates reference.fasta
-# 			samtools faidx reference.fasta
-# 			bwa index reference.fasta
+			# go through identified sequences and use as reference for alignment
+			while read seq_name; do
+				# create a fasta reference file with a single sequence, index it as required
+				python $SCRIPTS_DIR/extract_fasta.py "$seq_name" $ALL_FASTA # creates reference.fasta
+				samtools faidx reference.fasta
+				bwa index reference.fasta
 
-# 			# samtools v1.3.1
-# 			bwa mem reference.fasta $READS_1 $READS_2 | samtools view -b | samtools sort -o alignment.bam
+				# samtools v1.3.1
+				bwa mem reference.fasta $READS_1 $READS_2 | samtools view -b | samtools sort -o alignment.bam
 
-# 			samtools index alignment.bam
-# 			echo "[current] samtools index finished"
+				samtools index alignment.bam
+				echo "samtools index finished"
 
-# 			samtools mpileup -uf reference.fasta alignment.bam |
+				samtools mpileup -uf reference.fasta alignment.bam |
 
-# 			if [[ $(hostname) == 'orange' ]] ; then
-# 				bcftools call -c | python $CURDIR/mpileup2cons.py reference.fasta
-# 			else
-# 				# cluster 21
-# 				bcftools view -cg - | python $CURDIR/mpileup2cons.py reference.fasta
-# 			fi
+	# 			if [[ $(hostname) == 'orange' ]] ; then
+					bcftools call -c | python $SCRIPTS_DIR/mpileup2cons.py reference.fasta
+	# 			else
+	# 				# cluster 21
+	# 				bcftools view -cg - | python $SCRIPTS_DIR/mpileup2cons.py reference.fasta
+	# 			fi
 
-# 			# http://samtools.sourceforge.net/mpileup.shtml
-# 			# alternative but produces truncated consensus and ambiguous bases
-# 			# use vcfutils, skip first line which is the sequence ID, convert to a single line, stop after the + character (now have the consensus sequence)
-# 			# samtools mpileup -uf reference.fasta alignment.bam | bcftools view -cg - |
-# 				# vcfutils.pl vcf2fq | tail -n +2 | tr -d '\n' | cut -f1 -d +
+				# http://samtools.sourceforge.net/mpileup.shtml
+				# alternative but produces truncated consensus and ambiguous bases
+				# use vcfutils, skip first line which is the sequence ID, convert to a single line, stop after the + character (now have the consensus sequence)
+				# samtools mpileup -uf reference.fasta alignment.bam | bcftools view -cg - |
+					# vcfutils.pl vcf2fq | tail -n +2 | tr -d '\n' | cut -f1 -d +
 
-# 			echo "[current] writing sequence to file ..."
-# 			cat new_reference.fasta >> $CORR_SEQ
-# 			echo -e "[current] Output located at:\n"$CORR_SEQ
+				echo "writing sequence to file ..."
+				cat new_reference.fasta >> $CORR_SEQ
+				echo -e "Output located at:\n"$CORR_SEQ
 
-# 			# Even if we don't remove, they will be overwritten when the enxt sequence is processed.
-# 			rm -vf new_reference.fasta
-# 			rm -vf reference.fasta*
-# 			rm -vf alignment.bam*
+				# Even if we don't remove, they will be overwritten when the next sequence is processed.
+				rm -vf new_reference.fasta
+				rm -vf reference.fasta*
+				rm -vf alignment.bam*
 
-# 			echo "[current] sleeping for 10 then moving to next sequence ..." && sleep 10
+				echo "Done, moving to next sequence"
 
-# 		done <accepted_seq_names.txt
-# 		rm -vf accepted_seq_names.txt
-# 		echo "[current] sleeping for 10 then moving to next cell ..." && sleep 10
-# 	done
-# done
+			done <accepted_seq_names.txt
+			rm -vf accepted_seq_names.txt
+			echo "Done, moving to next cell"
+		done
+	done
+fi
 
 
 if [[ $TYPE == 't' ]]; then
